// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Rsbc.Dmf.Interfaces.IcbcAdapter.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CLNT
    {
        /// <summary>
        /// Initializes a new instance of the CLNT class.
        /// </summary>
        public CLNT()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CLNT class.
        /// </summary>
        public CLNT(CLNTINAM iNAM = default(CLNTINAM), double? wGHT = default(double?), string sEX = default(string), System.DateTime? bIDT = default(System.DateTime?), int? hGHT = default(int?), string sECK = default(string), CLNTADDR aDDR = default(CLNTADDR), CLNTDR1MST dR1MST = default(CLNTDR1MST))
        {
            INAM = iNAM;
            WGHT = wGHT;
            SEX = sEX;
            BIDT = bIDT;
            HGHT = hGHT;
            SECK = sECK;
            ADDR = aDDR;
            DR1MST = dR1MST;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "INAM")]
        public CLNTINAM INAM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WGHT")]
        public double? WGHT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SEX")]
        public string SEX { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "BIDT")]
        public System.DateTime? BIDT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HGHT")]
        public int? HGHT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SECK")]
        public string SECK { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADDR")]
        public CLNTADDR ADDR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DR1MST")]
        public CLNTDR1MST DR1MST { get; set; }

    }
}
