// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Rsbc.Dmf.Interfaces.IcbcAdapter.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CLNTDR1MST
    {
        /// <summary>
        /// Initializes a new instance of the CLNTDR1MST class.
        /// </summary>
        public CLNTDR1MST()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CLNTDR1MST class.
        /// </summary>
        public CLNTDR1MST(int? mSCD = default(int?), IList<int?> rSCD = default(IList<int?>), System.DateTime? rRDT = default(System.DateTime?), int? lNUM = default(int?), CLNTDR1MSTDR1STAT dR1STAT = default(CLNTDR1MSTDR1STAT), int? lCLS = default(int?), IList<CLNTDR1MSTDR1MEDNItem> dR1MEDN = default(IList<CLNTDR1MSTDR1MEDNItem>))
        {
            MSCD = mSCD;
            RSCD = rSCD;
            RRDT = rRDT;
            LNUM = lNUM;
            DR1STAT = dR1STAT;
            LCLS = lCLS;
            DR1MEDN = dR1MEDN;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MSCD")]
        public int? MSCD { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RSCD")]
        public IList<int?> RSCD { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "RRDT")]
        public System.DateTime? RRDT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LNUM")]
        public int? LNUM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DR1STAT")]
        public CLNTDR1MSTDR1STAT DR1STAT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LCLS")]
        public int? LCLS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DR1MEDN")]
        public IList<CLNTDR1MSTDR1MEDNItem> DR1MEDN { get; set; }

    }
}
