// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Rsbc.Dmf.Interfaces.IcbcAdapter.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CLNTDR1MSTDR1MEDNItem
    {
        /// <summary>
        /// Initializes a new instance of the CLNTDR1MSTDR1MEDNItem class.
        /// </summary>
        public CLNTDR1MSTDR1MEDNItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CLNTDR1MSTDR1MEDNItem class.
        /// </summary>
        public CLNTDR1MSTDR1MEDNItem(string mDSP = default(string), string mDSPDESC = default(string), int? iSOF = default(int?), string iSOFDESC = default(string), string mIDT = default(string), string mEDT = default(string), string pGN2 = default(string), string pGN1 = default(string))
        {
            MDSP = mDSP;
            MDSPDESC = mDSPDESC;
            ISOF = iSOF;
            ISOFDESC = iSOFDESC;
            MIDT = mIDT;
            MEDT = mEDT;
            PGN2 = pGN2;
            PGN1 = pGN1;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MDSP")]
        public string MDSP { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MDSP-DESC")]
        public string MDSPDESC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ISOF")]
        public int? ISOF { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ISOF-DESC")]
        public string ISOFDESC { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MIDT")]
        public string MIDT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MEDT")]
        public string MEDT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PGN2")]
        public string PGN2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PGN1")]
        public string PGN1 { get; set; }

    }
}
