// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Rsbc.Dmf.Interfaces.IcbcAdapter.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DR1STAT
    {
        /// <summary>
        /// Initializes a new instance of the DR1STAT class.
        /// </summary>
        public DR1STAT()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DR1STAT class.
        /// </summary>
        public DR1STAT(System.DateTime? eFDT = default(System.DateTime?), string eXDS = default(string), int? nMCD = default(int?), int? sECT = default(int?), System.DateTime? sRDT = default(System.DateTime?), string nECD = default(string))
        {
            EFDT = eFDT;
            EXDS = eXDS;
            NMCD = nMCD;
            SECT = sECT;
            SRDT = sRDT;
            NECD = nECD;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "EFDT")]
        public System.DateTime? EFDT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EXDS")]
        public string EXDS { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NMCD")]
        public int? NMCD { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SECT")]
        public int? SECT { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "SRDT")]
        public System.DateTime? SRDT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NECD")]
        public string NECD { get; set; }

    }
}
