name: Build on GitHub & Push to OpenShift

on:
  workflow_dispatch:

env:
  APP_NAME: demo_express
  # REGISTRY: image-registry.apps.silver.devops.gov.bc.ca/bde4f5-tools
  REGISTRY: ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_NAMESPACE }}

# defaults:
  # run:
  #   working-directory: ./app

jobs:
  build:
    name: Build Image
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.ACTOR }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build to Docker image
        uses: docker/build-push-action@v3
        with:
          # push: true
          context: ./app
          tags: |
            ${{ env.APP_NAME }}:latest

      - name: Login to Registry
        run:  echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login -u unused --password-stdin $REGISTRY

      - name: Tag Image
        run:  docker tag $APP_NAME:latest $REGISTRY/demo-express:latest

      - name: Push Image
        run:  docker push $REGISTRY/demo-express:latest
