// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pssg.Interfaces.Icbc.ViewModels
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DriverMedical
    {
        /// <summary>
        /// Initializes a new instance of the DR1MEDNITEM class.
        /// </summary>
        public DriverMedical()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DR1MEDNITEM class.
        /// </summary>
        public DriverMedical(string mDSP = default(string), string mDSPDESC = default(string), int? iSOF = default(int?), string iSOFDESC = default(string), System.DateTime? mIDT = default(System.DateTime?), System.DateTime? mEDT = default(System.DateTime?), string pGN2 = default(string), string pGN1 = default(string))
        {
            MedicalDisposition = mDSP;
            MedicalDispositionDescription = mDSPDESC;
            IssuingOffice = iSOF;
            IssuingOfficeDescription = iSOFDESC;
            MedicalIssueDate = mIDT;
            MedicalExamDate = mEDT;
            PGN2 = pGN2;
            PGN1 = pGN1;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MDSP")]
        public string MedicalDisposition { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MDSP-DESC")]
        public string MedicalDispositionDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ISOF")]
        public int? IssuingOffice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ISOF-DESC")]
        public string IssuingOfficeDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "MIDT")]
        public System.DateTime? MedicalIssueDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "MEDT")]
        public System.DateTime? MedicalExamDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PGN2")]
        public string PGN2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PGN1")]
        public string PGN1 { get; set; }

    }
}
