// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pssg.Interfaces.Icbc.ViewModels
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DriverStatus
    {
        /// <summary>
        /// Initializes a new instance of the DR1STAT class.
        /// </summary>
        public DriverStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DR1STAT class.
        /// </summary>
        public DriverStatus(System.DateTime? eFDT = default(System.DateTime?), string eXDS = default(string), string nMCD = default(string), string sECT = default(string), System.DateTime? sRDT = default(System.DateTime?), string nECD = default(string))
        {
            EffectiveDate = eFDT;            
            NewMasterStatusCode = nMCD;
            Section = sECT;
            StatusReviewDate = sRDT;
            NewExpandedStatus = nECD;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// The date that the status is added to the status segment
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]        
        public System.DateTime? EffectiveDate { get; set; }

        /// <summary>
        /// </summary>

        /// <summary>
        /// The new master status code that the expanded status is adding to the root segment
        /// </summary>        
        public string NewMasterStatusCode { get; set; }

        /// <summary>
        /// The message table, which the expanded status code originates from 
        /// </summary>        
        public string Section { get; set; }

        /// <summary>
        /// The date on which the status will expire
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]        
        public System.DateTime? StatusReviewDate { get; set; }

        /// <summary>
        /// The code for the status that is being added to the status segment
        /// </summary>
        public string NewExpandedStatus { get; set; }

    }
}
