# sample BA scenario
Scenario: * name of scenario *
    When I log in to the doctors' portal
    And I click on the ...
    And I click on the ...
    And I refresh the page
    And I wait for ...
    And I click on the ...
    And the page content is displayed
    And I click on the ...
    Then I log out of the portal
    And I click on the next button ...
