# sample BA scenario
Scenario: * name of scenario *
    When I log in to the doctors' portal
    And I click on the ...
    And I click on the ...
    And I refresh the page
    And I wait for ...
    And I click on the ...
    And the page content is displayed
    And I click on the ...
    Then I log out of the portal
    And I click on the next button ...

Scenario: Drivers licence numbers leading with zero display in Doctors' Portal
    When I log in to the doctors' portal
    And I click on the DMER Forms tab
    And I click on a DMER with a leading zero DL
    And I wait for the drivers licence field to have a value
    Then the correct DL number is displayed
