kind: Template
apiVersion: v1
metadata:
  name: dps-adapter-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    value: icbc-adapter
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Hostname
    name: HOST
    required: true
  - description: Image name
    name: IMAGENAME
    required: true
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging
  - description: JWT_TOKEN_KEY
    name: JWT_TOKEN_KEY
    value: Changeme
  - description: JWT_VALID_AUDIENCE
    name: JWT_VALID_AUDIENCE
    value: Changeme
  - description: JWT_VALID_ISSUER
    name: JWT_VALID_ISSUER
    value: Changeme
  - description: SERVICE_URL
    name: SERVICE_URL
    value: Changeme
  - description: BUCKET
    name: BUCKET
    value: Changeme
  - description: ACCESS_KEY
    name: ACCESS_KEY
    value: Changeme
  - description: SECRET_KEY
    name: SECRET_KEY
    value: Changeme
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"
      DOTNET_SSL_DIRS: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
      OPENSHIFT_BUILD_NAME: "1"
  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:
      ICBC_LOOKUP_SERVICE_URI: "${ICBC_LOOKUP_SERVICE_URI}"
      ICBC_LOOKUP_SERVICE_USERNAME: "${ICBC_LOOKUP_SERVICE_USERNAME}"
      ICBC_LOOKUP_SERVICE_PASSWORD: "${ICBC_LOOKUP_SERVICE_PASSWORD}"
      JWT_TOKEN_KEY: "${JWT_TOKEN_KEY}"
      JWT_VALID_AUDIENCE: "${JWT_VALID_AUDIENCE}"
      JWT_VALID_ISSUER: "${JWT_VALID_ISSUER}"

  - kind: Service
    apiVersion: v1
    metadata:
      annotations:
        service.alpha.openshift.io/serving-cert-secret-name: ${APP_NAME}-cert
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8088-tcp
          port: 8088
          protocol: TCP
          targetPort: 8088
      selector:
        deploymentconfig: ${APP_NAME}
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${HOST}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${APP_NAME}
        weight: 100
      tls:
        termination: passthrough
      wildcardPolicy: None

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}
      ingress:
        - ports:
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              env:
                - name: SPLUNK_COLLECTOR_URL
                  valueFrom:
                    secretKeyRef:
                      name: splunk
                      key: url
                - name: SPLUNK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: splunk
                      key: token
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-config
                - secretRef:
                    name: ${APP_NAME}-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/${IMAGENAME}:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - name: dp-keys
                  mountPath: /dpkeys
                - name: service-cert
                  mountPath: /var/run/secrets/service-cert
              livenessProbe:
                httpGet:
                  path: /hc/live
                  port: 8088
              startupProbe:
                httpGet:
                  path: /hc/ready
                  port: 8088
              readinessProbe:
                httpGet:
                  path: /hc/ready
                  port: 8088

          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp-keys
              persistentVolumeClaim:
              claimName: ${APP_NAME}-key-ring
            - name: service-cert
              secret:
                secretName: ${APP_NAME}-cert
              defaultMode: 420
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${IMAGENAME}:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  