kind: Template
apiVersion: v1
metadata:
  name: medical-portal-template

parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: app name
    name: APP_NAME
    required: true
  - description: image tag for deployments
    name: TAG
    required: true
  - description: host for routes
    name: HOST
    required: true
  - description: ASPNET runtime environment (Development/Staging/Production)
    name: RUNTIME_ENVIRONMENT
    value: Staging
  - description: eForms server url
    name: EFORMS_FORM_SERVER_URL
    required: true
  - description: fhir server url
    name: EFORMS_FHIR_SERVER_URL
    required: true
  - description: eForms vendor id
    name: EFORMS_VENDOR_ID
    required: true
  - description: eForms forms map
    name: EFORMS_FORMS_MAP
    required: true
  - description: oauth server url
    name: OAUTH_SERVER_URL
    required: true
  - description: oauth server client id
    name: OAUTH_CLIENTID
    required: true
  - description: oauth server client secret
    name: OAUTH_CLIENTSECRET
    required: true
  - description: oidc client id
    name: OIDC_CLIENTID
    required: true
  - description: oidc scopes
    name: OIDC_SCOPE
    value: "openid profile email phsa-adapter medical-portal-api"
  - description: CMS adapter client secret
    name: CMSADAPTER_CLIENT_SECRET
    required: true
  - description: CMS adapter server url
    name: CMSADAPTER_SERVER_URL
    required: true
  - description: CMS adapter server cert validation
    name: CMSADAPTER_VALIDATE_SERVER_CERTIFICATE
    value: "true"
  - description: CLINIC_ID
    name: CLINIC_ID
    value: "true"
  - description: CORS_ORIGINS
    name: CORS_ORIGINS
    value: "true"

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-doctors-api-config
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    data:
      ASPNETCORE_ENVIRONMENT: ${RUNTIME_ENVIRONMENT}
      KEY_RING_PATH: "/dpkeys"
      EFORMS__FHIRSERVERURL: ${EFORMS_FHIR_SERVER_URL}
      EFORMS__FORMSERVERURL: ${EFORMS_FORM_SERVER_URL}
      EFORMS__FORMSMAP: ${EFORMS_FORMS_MAP}
      CMS__SERVERURL: ${CMSADAPTER_SERVER_URL}
      CMS__VALIDATESERVERCERTIFICATE: ${CMSADAPTER_VALIDATE_SERVER_CERTIFICATE}
      app__cors__origins: ${CORS_ORIGINS}
  - kind: Secret
    apiVersion: v1
    type: Opaque
    metadata:
      name: ${APP_NAME}-doctors-api-secrets
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    stringData:
      EFORMS__EMRVENDORID: ${EFORMS_VENDOR_ID}
      AUTH__INTROSPECTION__AUTHORITY: ${OAUTH_SERVER_URL}
      AUTH__INTROSPECTION__CLIENTID: ${OAUTH_CLIENTID}
      AUTH__INTROSPECTION__CLIENTSECRET: ${OAUTH_CLIENTSECRET}
      AUTH__TOKEN__AUTHORITY: ${OAUTH_SERVER_URL}
      AUTH__OIDC__ISSUER: ${OAUTH_SERVER_URL}
      AUTH__OIDC__SCOPE: ${OIDC_SCOPE}
      AUTH__OIDC__CLIENTID: ${OIDC_CLIENTID}
      CMS__CLIENTSECRET: ${CMSADAPTER_CLIENT_SECRET}
      CLINIC_ID: ${CLINIC_ID}

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-medical-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APP_NAME}-medical-portal-api
      type: ClusterIP

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-medical-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      ports:
        - name: 2015-tcp
          port: 2015
          protocol: TCP
          targetPort: 2015
      selector:
        deploymentconfig: ${APP_NAME}-medical-portal-ui
      type: ClusterIP

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-medical-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      host: ${HOST}
      path: /rsbc-dfp-medical-portal
      port:
        targetPort: 2015-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-medical-portal-ui
        weight: 100

  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: ${APP_NAME}-medical-portal
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      podSelector:
        matchLabels:
          app: ${APP_NAME}-medical-portal
      ingress:
        - ports:
            - protocol: TCP
              port: 2015
            - protocol: TCP
              port: 8080

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-medical-portal-api
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-medical-portal-api
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-medical-portal
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-medical-portal-api
        spec:
          containers:
            - name: medical-portal-api
              envFrom:
                - configMapRef:
                    name: ${APP_NAME}-doctors-api-config
                - secretRef:
                    name: ${APP_NAME}-doctors-api-secrets
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/medical-portal-api:${TAG}
              imagePullPolicy: Always
              volumeMounts:
                - mountPath: /dpkeys
                  name: dp-keys
              livenessProbe:
                httpGet:
                  path: /hc/live
                  port: 8080
              startupProbe:
                httpGet:
                  path: /hc/ready
                  port: 8080
              readinessProbe:
                httpGet:
                  path: /hc/ready
                  port: 8080
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: dp-keys
              persistentVolumeClaim:
                claimName: ${APP_NAME}-doctors-key-ring
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - medical-portal-api
            from:
              kind: ImageStreamTag
              name: medical-portal-api:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
      name: ${APP_NAME}-medical-portal-ui
      namespace: ${NAMESPACE_PREFIX}-${ENV}
    spec:
      replicas: 2
      selector:
        deploymentconfig: ${APP_NAME}-medical-portal-ui
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}-medical-portal
            app.kubernetes.io/part-of: ${APP_NAME}
            deploymentconfig: ${APP_NAME}-medical-portal-ui
        spec:
          containers:
            - name: medical-portal-ui
              env:
                - name: API_URL
                  value: ${APP_NAME}-medical-portal-api:8080
              image: docker-registry.default.svc:5000/${NAMESPACE_PREFIX}-tools/medical-portal-ui:${TAG}
              imagePullPolicy: Always
              ports:
                - containerPort: 2015
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              livenessProbe:
                httpGet:
                  path: /
                  port: 2015
              startupProbe:
                httpGet:
                  path: /
                  port: 2015
              readinessProbe:
                httpGet:
                  path: /
                  port: 2015
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - medical-portal-ui
            from:
              kind: ImageStreamTag
              name: medical-portal-ui:${TAG}
              namespace: ${NAMESPACE_PREFIX}-tools

  - kind: "PersistentVolumeClaim"
    apiVersion: "v1"
    metadata:
      name: ${APP_NAME}-doctors-key-ring
      namespace: ${NAMESPACE_PREFIX}-${ENV}
      labels:
        app: ${APP_NAME}-medical-portal
        app.kubernetes.io/part-of: ${APP_NAME}
    spec:
      accessModes:
        - "ReadWriteMany"
      resources:
        requests:
          storage: "100Mi"
