// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pssg.Interfaces.Icbc.Models
{
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CLNT4
    {
        /// <summary>
        /// Initializes a new instance of the CLNT class.
        /// </summary>
        public CLNT4()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CLNT class.
        /// </summary>
        public CLNT4(INAM iNAM = default(INAM), double? wGHT = default(double?), string sEX = default(string), System.DateTime? bIDT = default(System.DateTime?), double? hGHT = default(double?), string sECK = default(string), ADDR aDDR = default(ADDR), DR1MST4 dR1MST = default(DR1MST4))
        {
            INAM = iNAM;
            WGHT = wGHT;
            SEX = sEX;
            BIDT = bIDT;
            HGHT = hGHT;
            SECK = sECK;
            ADDR = aDDR;
            DR1MST = dR1MST;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "INAM")]
        public INAM INAM { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WGHT")]
        public double? WGHT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SEX")]
        public string SEX { get; set; }

        /// <summary>
        /// </summary>
        [JsonConverter(typeof(DateJsonConverter))]
        [JsonProperty(PropertyName = "BIDT")]
        public System.DateTime? BIDT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HGHT")]
        public double? HGHT { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SECK")]
        public string SECK { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADDR")]
        public ADDR ADDR { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DR1MST")]
        public DR1MST4 DR1MST { get; set; }

    }
}
