// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pssg.Interfaces.Icbc.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class INAM
    {
        /// <summary>
        /// Initializes a new instance of the INAM class.
        /// </summary>
        public INAM()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the INAM class.
        /// </summary>
        public INAM(string sURN = default(string), string gIV1 = default(string), string gIV3 = default(string), string gIV2 = default(string))
        {
            SURN = sURN;
            GIV1 = gIV1;
            GIV3 = gIV3;
            GIV2 = gIV2;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SURN")]
        public string SURN { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GIV1")]
        public string GIV1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GIV3")]
        public string GIV3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GIV2")]
        public string GIV2 { get; set; }

    }
}
