// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Pssg.Interfaces.Icbc.FlatFileModels
{
    using FileHelpers;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using System.Linq;

    [FixedLengthRecord()]
    public class NewDriver
    {
        // LNUM Driver License Number Char(7) - example 2222222
        [FieldFixedLength(7)]
        public string LicenseNumber { get; set;}

        // CLNO Client Number Char(9) - example 022222224
        [FieldFixedLength(9)]
        public string ClientNumber { get; set;}

        // SURN Surname Char(35) - example EXPERIMENTAL_______________________
        [FieldFixedLength(35)] 
        public string Surname {  get; set;}

        // MIDT Medical Issue Date Char(10) - example 2012-01-01
        [FieldFixedLength(10)]
        public string MedicalIssueDate {  get; set;}

        // MDTP Medical Type Char(1) - example 1
        [FieldFixedLength(1)]
        public string MedicalType { get; set;}

        // SEX Sex Char(1) - example M
        [FieldFixedLength(1)]
        public string Sex { get; set; }

        // BIDT Birth Date Char(10) - example 2002-02-01
        [FieldFixedLength(10)]
        public string BirthDate { get; set; }

        // RRSR License Expiry Date Char(10) - example 2004-01-01
        [FieldFixedLength(10)]
        public string LicenceExpiryDate { get; set; }

        // LMDT Last Medical Date Char(10) - example 1998-01-01
        [FieldFixedLength(10)] 
        public string LastMedicalDate { get; set; }

        // LEDT Last Exam Date Char(10) - example 2002-04-040100
        [FieldFixedLength(10)]
        public string LastExamDate { get; set; }

        // Add Date Char(10)
        [FieldFixedLength(10)]
        public string AddDate { get; set; }        

        // MSCD Master Status Code Char(1) 
        [FieldFixedLength(1)]
        public string MasterStatusCode { get; set; }

        // LCLS License Class Char(3)
        [FieldFixedLength(3)]
        public string LicenseClass { get; set; }
}
}
