name: ci-icbc-adapter

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - 'icbc-adapter/src/**'
      - '.github/workflows/ci-icbc-adapter.yml'
  workflow_dispatch:

env:
  IMAGE_NAME: icbc-adapter
  solution-folder: icbc-adapter/src/ 
  RUN_NUMBER: ${{ github.run_number }}
  BUILD_PREFIX: ${{ vars.versionprefix }}
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rlespinasse/git-commit-data-action@v1.x
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Setup .NET 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
      - name: Install dependencies
        run: dotnet restore
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - name: Install coverlet for code coverage
        run: dotnet tool install -g coverlet.console --version 1.7.2
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - name: Test
        run: |          
          dotnet test -c Release --no-restore --verbosity normal --blame-hang --blame-hang-timeout 30s
        timeout-minutes: 10          
        working-directory: ${{env.working-directory}}${{env.solution-folder}}

      - name: Generate code coverage
        working-directory: ${{env.working-directory}}${{env.solution-folder}}
        run: |
          mkdir -p CovTestResults
          rm -rf .Pssg.Unit.Tests.Interfaces.Icbc/TestResults
          dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings --no-restore
          mv Pssg.Unit.Tests.Interfaces.Icbc/TestResults/*/* ./CovTestResults/
          head CovTestResults/coverage.opencover.xml      
      
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          # User defined upload name. Visible in Codecov UI
          name: DMF-MEDICAL-PORTAL-API
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{env.working-directory}}${{env.solution-folder}}CovTestResults/coverage.opencover.xml
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: unittests
          # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
          env_vars: C#
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: true

      - name: Build image
        run: docker build --build-arg BUILD_ID --build-arg BUILD_VERSION="$BUILD_PREFIX`expr $RUN_NUMBER % 256`" . --file ./icbc-adapter/src/Dockerfile --tag $IMAGE_NAME
